## ç½‘ç«™è®¾ç½®
# æ ‡é¢˜
title: Blog
# é€‰é¡¹å¡æ ‡é¢˜
SEOTitle: ğŸ¦Œ | ğŸ¦…ğŸ’»âšª Blog
# é¦–é¡µèƒŒæ™¯å›¾ç‰‡
header-img: img/post-bg-debug.png
# é‚®ç®±è®¾ç½®
email: 18615371082@163.com
# ç½‘ç«™ä»‹ç»
description: "I guess it comes down to a simple choice:get busy living or get busy dying."
# å…³é”®è¯
keyword: "Java, Vue.js"
# åšå®¢è®¿é—®é“¾æ¥
url: "https://SuperNu/SuperNu.github.io"
# '/blog' if your blog hosted on 'host/blog'
baseurl: ""

## ä¾§è¾¹æ è®¾ç½®
# æ˜¯å¦å¼€å¯ä¾§è¾¹æ  true å¼€å§‹ false å…³é—­
sidebar: true
# ä¾§è¾¹æ æè¿°è¯­å¥
sidebar-about-description: "WHY CLIMB MOUNT EVEREST? 'BECAUSE IT'S THERE'"
# ä¾§è¾¹æ å¤´åƒ
sidebar-avatar: /img/sidebar-avatar.jpg

## ç¤¾äº¤ç½‘ç«™è®¾ç½®
RSS: false
# å¾®åš æ‰“å¼€ä¸ªäººä¸»é¡µæˆªå–ç”¨æˆ·ç¼–å· ä¾‹å¦‚ä¸ªäººä¸»é¡µç½‘å€ä¸ºhttps://weibo.com/u/5089298519 å¡«å†™ 5089298519
weibo_username:     5089298519
# çŸ¥ä¹ä¸ªäººé¡µé¢ å¡«å†™ç”¨æˆ·å
zhihu_username:     zhen-lue-meng-95-95
# GitHubä¸ªäººé¡µé¢ å¡«å†™ç”¨æˆ·å
github_username:    SuperNu
# facebookä¸ªäººé¡µé¢ å¡«å†™ç”¨æˆ·å
#facebook_username:  100024292873470
# ç®€ä¹¦ä¸ªäººé¡µé¢æˆªå–ç”¨æˆ·ç¼–å· ä¸å¾®åšåŒç†
jianshu_username:   30a3617d59f2
# twitterä¸ªäººé¡µé¢ å¡«å†™ç”¨æˆ·å
#twitter_username:   zhoudalu

## æ„å»ºè®¾ç½®
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

## Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

## Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

## è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: superZhoudalu

## Gitalk
gitalk:
  #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  enable: true
  #ç”Ÿæˆçš„clientID
  clientID: bde9d2bff0cd1048efeb
  #ç”Ÿæˆçš„clientSecret
  clientSecret: 4be7e16501b7e64eb16568815fe5948fc3007ad1
  #ä»“åº“åç§°
  repo: superzhoudalu.github.io
  #githubç”¨æˆ·å
  owner: superZhouDaLu
  admin: superZhouDaLu
  #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©
  distractionFreeMode: true

## ç»Ÿè®¡
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-135281137-1'
# é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto
ga_domain: https://aigq.me

## æ ‡ç­¾è®¾ç½®
# æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-tags: true
# ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ
featured-condition-size: 0

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

## å‹æƒ…é“¾æ¥
friends: [
    {
        title: "ITèµ„æºç½‘",
        href: "https://www.itresource.org/forum-37-1.html"
    },{
        title: "jsä»£ç ç½‘",
        href: "https://www.jsdaima.com/"
    },{
        title: "java1234",
        href: "http://download.java1234.com/"
    },{
        title: "é…·å£³",
        href: "https://coolshell.cn/"
    }
]
